name: DevOps Test - Anthony

on:
    push:
        branches: [main]

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - run: ls -al
            - uses: actions/checkout@v3
            - run: ls -al
            - run: cat README.md

            - run: npm ci
            - run: npm run build --if-present
            - run: |
                  cd .next;
                  mv ./static ./standalone/.next/;
                  mv standalone ..;

            # Runs a set of commands using the runners shell
#            - name: making tar files
 #             run: |
  #              pwd;
   #             tar -cvf deploy.tar ./standalone;

            - name: Upload files via scp
              uses: appleboy/scp-action@master
              with:
                  host: ${{ secrets.AWS_SSH_HOST }}
                  username: ${{ secrets.AWS_SSH_USERNAME }}
                  key: ${{ secrets.AWS_SSH_KEY }}
                  source: "standalone"
                  target: "~"

            - name: SSH Commands
              uses: appleboy/ssh-action@v0.1.7
              with:
                  host: ${{ secrets.AWS_SSH_HOST }}
                  username: ${{ secrets.AWS_SSH_USERNAME }}
                  key: ${{ secrets.AWS_SSH_KEY }}
                  script_stop: true
                  script: |
                      cd ~/standalone;
                      node server.js;
