name: DevOps Test - Anthony

on:
    push:
        branches: [main]

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - run: ls -al
            - uses: actions/checkout@v3
            - run: ls -al
            - run: cat README.md

            - run: npm ci
            - run: npm run build --if-present
            - run: |
                  cd .next;
                  mv ./static ./standalone/.next/;
                  mkdir ../buildresult
                  mv standalone ../buildresult;

            # Runs a set of commands using the runners shell
#            - name: making tar files
 #             run: |
  #              pwd;
   #             tar -cvf deploy.tar ./standalone;
            - name: upload for deploy job
              uses: actions/upload-artifact@v3.1.2
              with:
                name: buildresult
                path: buildresult
    deploy:
        needs: build
        runs-on: ubuntu-latest
        steps:
            - name: download build result
              uses: actions/download-artifact@v3.0.2
              with: 
                name: buildresult
            
            - name: check build result
              run: |
                pwd;
                ls;

            - name: Upload files via scp
              uses: appleboy/scp-action@master
              with:
                  host: ${{ secrets.AWS_SSH_HOST }}
                  username: ${{ secrets.AWS_SSH_USERNAME }}
                  key: ${{ secrets.AWS_SSH_KEY }}
                  source: "standalone"
                  target: "~"
                  rm: true

            - name: SSH Commands
              uses: appleboy/ssh-action@v0.1.7
              with:
                  host: ${{ secrets.AWS_SSH_HOST }}
                  username: ${{ secrets.AWS_SSH_USERNAME }}
                  key: ${{ secrets.AWS_SSH_KEY }}
                  script_stop: true
                  script: |
                      cd ~/standalone;
                      nohup node server.js 1>/dev/null 2>&1 &
